# fly.toml app configuration file generated for back-end-prod on 2023-12-22T19:09:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "back-end-prod"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3100
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  max_machines_running = 5
  processes = ["app"]
  backend = "app"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096
